// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

/// @title LibProdDeployV4
/// @notice V4 production deployment pins for the ST0x contract set on Base,
/// rebuilt against the audited rain.vats `sol-v0.1.6` tag (Renascence Labs
/// audit dated 2026-06; H01 "ERC1155 acceptance callback enables persistent
/// operator approval via `_msgSender` spoofing" fixed at upstream commit
/// `5275093` and reflected as the 0.1.6 Soldeer pin in `foundry.toml`).
/// Every deterministic Zoltu address derives from the compiled bytecode, so
/// every ST0x contract whose source-or-dependency tree changed under the
/// rain.vats bump gets a new V4 address here.
///
/// **The clone (`STOX_PROD_AUTHORISER_V4_CLONE`) is still `address(0)`** —
/// it gets hydrated by the V4 authoriser deploy script (sibling PR), which
/// is the only entry that isn't deterministic at lib-author time. Every
/// other address + codehash pair is the Zoltu-deterministic value generated
/// by `script/BuildPointers.sol` against rain.vats 0.1.6 and mirrors the
/// `DEPLOYED_ADDRESS` constants in `src/generated/*.pointers.sol`.
///
/// Naming convention (per Josh + DM, 2026-05-31): the rain.vats tag is
/// encoded in each deployed-contract constant name (`_RAIN_VATS_0_1_6`) so a
/// future tag bump produces a new constant rather than silently overwriting
/// an existing one. The lib name itself is generic (`LibProdDeployV4`) —
/// Soldeer's import path already encodes the version at the dependency
/// boundary, so the lib name doesn't need to.
///
/// The frozen pre-V4 deployments are pinned in `LibProdDeployV1` and
/// `LibProdDeployV2` as audit trails; active source and scripts reference this
/// (latest) lib.
library LibProdDeployV4 {
    /// @notice The rain.vats tag whose audited build these constants pin.
    /// Encoded in every deployed-contract constant name (e.g.
    /// `STOX_RECEIPT_RAIN_VATS_0_1_6`) so a future tag bump produces a new
    /// constant alongside this one rather than silently overwriting.
    /// @dev String constant, present only as a written reminder — Solidity has
    /// no preprocessor so future renames must be done by hand in the source.
    string constant RAIN_VATS_TAG = "RAIN_VATS_0_1_6";

    /// @notice The beacon initial owner. Resolves to rainlang.eth. Unchanged
    /// across V1 / V2 / V3 / V4; this is the EOA that receives ownership at
    /// deploy time and is migrated to the ST0x token-owner Safe by
    /// `LibProdMigrateBeaconOwnership`.
    address constant BEACON_INITIAL_OWNER = address(0x8E4bdeec7CEB9570D440676345dA1dCe10329f5b);

    // =========================================================================
    // Deployed-contract pointers for the audited rain.vats 0.1.6 build.
    //
    // Each `_RAIN_VATS_0_1_6` constant pair is the deterministic Zoltu
    // address and its runtime codehash for the ST0x contract compiled against
    // `rain-vats = "0.1.6"` (see `foundry.toml`). The addresses match the
    // `DEPLOYED_ADDRESS` constants in `src/generated/*.pointers.sol` — that
    // file is the authoritative source generated by
    // `script/BuildPointers.sol`. The codehashes here are
    // `keccak256(RUNTIME_CODE)` from the same pointer files; a future
    // `BuildPointers` run must regenerate them in lockstep with any rain.vats
    // bump.
    // =========================================================================

    address constant STOX_RECEIPT_RAIN_VATS_0_1_6 = address(0x2dF5cFE6d688EF9fF1B7c59A499D254b1527b286);
    bytes32 constant STOX_RECEIPT_CODEHASH_RAIN_VATS_0_1_6 =
        0x06fffbad12ea80897d55aab5d4f1cd3f34f674237db44a148cc133334a0cca54;

    address constant STOX_RECEIPT_VAULT_RAIN_VATS_0_1_6 = address(0xD7f91c1C6e6e651Ec3F1Fd707aF7CbB7526206e1);
    bytes32 constant STOX_RECEIPT_VAULT_CODEHASH_RAIN_VATS_0_1_6 =
        0x22aa77aa9ffec4d290a8cacbcd8444b85761b6a1fb77c3f1b1a73490a7d9f972;

    address constant STOX_WRAPPED_TOKEN_VAULT_RAIN_VATS_0_1_6 = address(0x0D99e0174DbF885ceD6AE8dEb939b0F890450099);
    bytes32 constant STOX_WRAPPED_TOKEN_VAULT_CODEHASH_RAIN_VATS_0_1_6 =
        0x6de4c556c1811293da4ad2e509ee476f3eb635f019845087e1d2777a1b272034;

    address constant STOX_UNIFIED_DEPLOYER_RAIN_VATS_0_1_6 = address(0x66f8435Ea24deb7E9b4138c2303E1693DC1875f4);
    bytes32 constant STOX_UNIFIED_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6 =
        0xd3a33fc7bf6717f736653abf8de146b784208d33bfaaafd04297d8f26d81cef7;

    address constant STOX_WRAPPED_TOKEN_VAULT_BEACON_RAIN_VATS_0_1_6 =
        address(0x9FD790f65CA3aF2772358c653F097f0a4c7EE7d2);
    bytes32 constant STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_RAIN_VATS_0_1_6 =
        0x8e95867e52db417944afd90f3b6c3c980962831e8a944e7f6958ba8f8cc10630;

    address constant STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RAIN_VATS_0_1_6 =
        address(0x679ab223dAb158Ea93e1a4F49104DE436C58eAb8);
    bytes32 constant STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6 =
        0x4637b099fe9279a8d4d88d9176ccadf92b20970eaf0b57b51997756d479ef43b;

    address constant STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RAIN_VATS_0_1_6 =
        address(0xbe5f05C4576e6D3e7bCCb4E64f08fc4F46Adf0cA);
    bytes32 constant STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6 =
        0xa2c4bd29f36bc6636938f3ad66e6de5d126ce41ed3134bed166cde259d5775ad;

    /// @dev The `ST0xOrchestrator` implementation contract. Parameterless
    /// (Initializable) — deployed once via Zoltu and pointed at by the
    /// beacon inside `StoxST0xOrchestratorBeaconSetDeployer`. Per-token
    /// orchestrators are `BeaconProxy` clones minted by the beacon deployer.
    address constant ST0X_ORCHESTRATOR_RAIN_VATS_0_1_6 = address(0x1BAbc865B0EA299CB6Ca910802799b4698885565);
    bytes32 constant ST0X_ORCHESTRATOR_CODEHASH_RAIN_VATS_0_1_6 =
        0x48a234b4272fe079782a9322eff0b1356e75c04cb9c2592fe9bdc568d16a533b;

    /// @dev `StoxST0xOrchestratorBeaconSetDeployer` — Zoltu-deployable
    /// concrete deployer with `BEACON_INITIAL_OWNER` and the impl above
    /// baked in. Anyone can call `deploy(owner)` to mint a
    /// `BeaconProxy`-cloned singleton orchestrator.
    address constant STOX_ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RAIN_VATS_0_1_6 =
        address(0x2ACf534FC1648da23800Eefe93aCe18e74523C80);
    bytes32 constant STOX_ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6 =
        0x076337d0c10448b338fdcd7a122284efa59bbd1ae9e08a5c0226a85e46f183d4;

    /// @dev The corporate-action-aware authoriser impl. The clone deployed
    /// for the issuer (see `STOX_PROD_AUTHORISER_V4_CLONE` below) points
    /// at this impl via EIP-1167.
    address constant STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RAIN_VATS_0_1_6 =
        address(0x2EA0d35d0B1F57C42e6130f298930228bCbFDe9b);
    bytes32 constant STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_RAIN_VATS_0_1_6 =
        0xf8a1d9b2fa068bae3c1a607434db48364a5cdab3020bd7e315ed2662a3b35b5f;

    address constant STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RAIN_VATS_0_1_6 =
        address(0xeaD68E489Cb19453b294dc46a3A5710b0d46d17F);
    bytes32 constant STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_RAIN_VATS_0_1_6 =
        0x4d94318cde48f1bc20f97e00aefad84bfb7c9db15c81b882862e127b05e06e15;

    /// @dev The corporate-actions facet. The receipt vault's `fallback()`
    /// hardcodes this address and delegatecalls every non-matching selector
    /// here, so a facet bytecode change forces a vault impl redeploy too. With
    /// the new rain.vats tag the receipt vault impl is rebuilt, so this facet
    /// is rebuilt in lock-step.
    address constant STOX_CORPORATE_ACTIONS_FACET_RAIN_VATS_0_1_6 = address(0xB7e24412126ad6A2Ce19cbd79FD11B68e7F30cf6);
    bytes32 constant STOX_CORPORATE_ACTIONS_FACET_CODEHASH_RAIN_VATS_0_1_6 =
        0xd91520075de1eb2e8fdf042fde3475ee89feb3942306e5d6d5c710273fefc080;

    /// @notice The V4 production authoriser clone — an EIP-1167 minimal
    /// proxy of `STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RAIN_VATS_0_1_6`
    /// that the upgrade script `setAuthorizer`s every production receipt
    /// vault onto, replacing the current pre-V3 clone pinned in
    /// `LibAuthoriserInvariants.STOX_PROD_AUTHORISER`.
    ///
    /// **PLACEHOLDER** (`address(0)` literal) until the clone is deployed
    /// against the V4 impl as a one-off ops step (initialised with the
    /// ST0x token-owner Safe as `initialAdmin`, then the non-admin grants
    /// from `LibAuthoriserInvariants.expectedGrants()` are mirrored onto
    /// it). The clone's address is not deterministic ahead of time (Rain
    /// `CloneFactory` uses non-deterministic `Clones.clone`); the
    /// post-deploy edit hand-writes the real literal in place of
    /// `address(0)` here.
    ///
    /// Lives in this lib (the deploy artifacts pin) rather than in
    /// `LibAuthoriserInvariants` because it's a deploy target, not a
    /// current-state invariant. Post-swap, `LibAuthoriserInvariants.STOX_PROD_AUTHORISER`
    /// updates to this address; the constant here is the immutable
    /// historical record of the V4 artifact.
    address constant STOX_PROD_AUTHORISER_V4_CLONE = address(0);

    /// @notice The pinned EIP-1167 runtime codehash for
    /// `STOX_PROD_AUTHORISER_V4_CLONE`. Deterministic from the V4 impl
    /// address embedded in the minimal-proxy runtime
    /// (`363d3d373d3d3d363d73<impl>5af43d82803e903d91602b57fd5bf3`); the
    /// invariant uses it to prove the clone hasn't been etched over.
    ///
    /// **PLACEHOLDER** — fill in once the V4 impl address is known and the
    /// clone is deployed. Easiest path: compute via
    /// `keccak256(abi.encodePacked(hex"363d3d373d3d3d363d73", v4Impl, hex"5af43d82803e903d91602b57fd5bf3"))`.
    bytes32 constant STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH = bytes32(0);
}
