// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {DeploySuite} from "../abstract/RainDeploySuitesBase.sol";

import {LibStoxCorporateActionsFacetReleased} from "./LibStoxCorporateActionsFacetReleased.sol";

import {LibStoxReceiptReleased} from "./LibStoxReceiptReleased.sol";

import {LibStoxReceiptVaultReleased} from "./LibStoxReceiptVaultReleased.sol";

import {LibStoxWrappedTokenVaultReleased} from "./LibStoxWrappedTokenVaultReleased.sol";

import {LibStoxWrappedTokenVaultBeaconReleased} from "./LibStoxWrappedTokenVaultBeaconReleased.sol";

import {
    LibStoxWrappedTokenVaultBeaconSetDeployerReleased
} from "./LibStoxWrappedTokenVaultBeaconSetDeployerReleased.sol";

import {
    LibStoxOffchainAssetReceiptVaultBeaconSetDeployerReleased
} from "./LibStoxOffchainAssetReceiptVaultBeaconSetDeployerReleased.sol";

import {LibStoxUnifiedDeployerReleased} from "./LibStoxUnifiedDeployerReleased.sol";

import {
    LibStoxOffchainAssetReceiptVaultAuthorizerV1Released
} from "./LibStoxOffchainAssetReceiptVaultAuthorizerV1Released.sol";

import {
    LibStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1Released
} from "./LibStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1Released.sol";

import {LibST0xOrchestratorReleased} from "./LibST0xOrchestratorReleased.sol";

import {LibST0xOrchestratorBeaconSetDeployerReleased} from "./LibST0xOrchestratorBeaconSetDeployerReleased.sol";

/// @title LibReleasedSuites
/// @notice Every frozen release this repo has cut, of every contract it
/// deploys: the per-contract released libs concatenated, in declaration
/// order.
///
/// There is one released lib per deployed contract because a release freezes
/// every contract it names into a single tag directory, so a lib that took
/// the record whole would give another contract's snapshot this contract's
/// suite key and collide with its own entry for that tag. This is where
/// those libs meet, and it is emitted from the same list that wrote them --
/// so a contract that is generated, aliased and frozen cannot be missing
/// from the declaration, and a release missing from the declaration is a
/// release every check quietly stops asking about.
library LibReleasedSuites {
    /// Every released suite, in declaration order.
    /// @return The released suites.
    function releasedSuites() internal pure returns (DeploySuite[] memory) {
        DeploySuite[][] memory released = new DeploySuite[][](12);
        released[0] = LibStoxCorporateActionsFacetReleased.releasedSuites();
        released[1] = LibStoxReceiptReleased.releasedSuites();
        released[2] = LibStoxReceiptVaultReleased.releasedSuites();
        released[3] = LibStoxWrappedTokenVaultReleased.releasedSuites();
        released[4] = LibStoxWrappedTokenVaultBeaconReleased.releasedSuites();
        released[5] = LibStoxWrappedTokenVaultBeaconSetDeployerReleased.releasedSuites();
        released[6] = LibStoxOffchainAssetReceiptVaultBeaconSetDeployerReleased.releasedSuites();
        released[7] = LibStoxUnifiedDeployerReleased.releasedSuites();
        released[8] = LibStoxOffchainAssetReceiptVaultAuthorizerV1Released.releasedSuites();
        released[9] = LibStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1Released.releasedSuites();
        released[10] = LibST0xOrchestratorReleased.releasedSuites();
        released[11] = LibST0xOrchestratorBeaconSetDeployerReleased.releasedSuites();

        uint256 total = 0;
        for (uint256 i = 0; i < released.length; i++) {
            total += released[i].length;
        }

        DeploySuite[] memory suites = new DeploySuite[](total);

        uint256 offset = 0;
        for (uint256 i = 0; i < released.length; i++) {
            for (uint256 j = 0; j < released[i].length; j++) {
                suites[offset + j] = released[i][j];
            }
            offset += released[i].length;
        }

        return suites;
    }
}
