// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2026 S01 Issuer GmbH
pragma solidity =0.8.25;

import {IBeacon} from "@openzeppelin-contracts-5.6.1/proxy/beacon/IBeacon.sol";
import {UpgradeableBeacon} from "@openzeppelin-contracts-5.6.1/proxy/beacon/UpgradeableBeacon.sol";
import {BeaconProxy} from "@openzeppelin-contracts-5.6.1/proxy/beacon/BeaconProxy.sol";
import {ERC165} from "@openzeppelin-contracts-5.6.1/utils/introspection/ERC165.sol";

import {ST0xOrchestrator} from "../ST0xOrchestrator.sol";
import {LibProdDeployV4} from "../../lib/LibProdDeployV4.sol";
import {IST0xOrchestratorBeaconSetDeployerV1} from "../../interface/IST0xOrchestratorBeaconSetDeployerV1.sol";

/// Thrown when `deploy` is called with `owner == address(0)`.
error ZeroOwner();

/// @title ST0xOrchestratorBeaconSetDeployer
/// @notice Deploys `ST0xOrchestrator` singletons as `BeaconProxy` instances
/// pointing at a shared beacon owned by the ST0x owner multisig. The
/// orchestrator is a singleton — one instance serves every token — so a
/// deployment is not bound to any vault. The beacon is retained so a single
/// upgrade rolls the deployed orchestrator(s) forward at once, and so a
/// future distinct token set could be served by a separate orchestrator on
/// its own beacon; for now exactly one is deployed.
///
/// The beacon's initial owner and implementation are hardcoded from
/// `LibProdDeployV4`, so the constructor takes no dynamic input and this
/// contract is Zoltu-deployable directly — its deterministic address is
/// generated by `script/BuildPointers.sol` like every other deployed
/// contract. Unlike the vault beacon-set deployers, whose parameterised base
/// lives in the `rain-vats` dependency and therefore needs a `Stox…` subclass
/// to fix the config for Zoltu, this deployer's logic is local to this repo,
/// so it is the concrete Zoltu contract itself — no subclass.
contract ST0xOrchestratorBeaconSetDeployer is ERC165, IST0xOrchestratorBeaconSetDeployerV1 {
    /// The beacon every deployed orchestrator proxy points at.
    IBeacon public immutable iOrchestratorBeacon;

    constructor() {
        iOrchestratorBeacon = new UpgradeableBeacon(
            LibProdDeployV4.ST0X_ORCHESTRATOR_RAIN_VATS_0_1_7, LibProdDeployV4.BEACON_INITIAL_OWNER
        );
    }

    /// @notice Deploy an `ST0xOrchestrator` singleton owned by `owner`.
    /// Callable by anyone — no auth on the deployer; the deployed instance's
    /// own `DEFAULT_ADMIN_ROLE` (held by `owner`) governs it.
    function deploy(address owner) external returns (address) {
        if (owner == address(0)) revert ZeroOwner();

        bytes memory initData = abi.encodeCall(ST0xOrchestrator.initialize, (owner));
        BeaconProxy proxy = new BeaconProxy(address(iOrchestratorBeacon), initData);

        emit Deployment(msg.sender, address(proxy), owner);
        return address(proxy);
    }

    /// @inheritdoc ERC165
    function supportsInterface(bytes4 interfaceId) public view override returns (bool) {
        return
            interfaceId == type(IST0xOrchestratorBeaconSetDeployerV1).interfaceId
                || super.supportsInterface(interfaceId);
    }
}
