// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {LibRainDeploy} from "rain-deploy-0.1.4/src/lib/LibRainDeploy.sol";
import {LibProdDeployV4} from "../../../src/lib/LibProdDeployV4.sol";
import {StoxReceipt} from "../../../src/concrete/StoxReceipt.sol";
import {StoxReceiptVault} from "../../../src/concrete/StoxReceiptVault.sol";
import {StoxWrappedTokenVault} from "../../../src/concrete/StoxWrappedTokenVault.sol";
import {StoxUnifiedDeployer} from "../../../src/concrete/deploy/StoxUnifiedDeployer.sol";
import {StoxWrappedTokenVaultBeacon} from "../../../src/concrete/StoxWrappedTokenVaultBeacon.sol";
import {
    StoxWrappedTokenVaultBeaconSetDeployer
} from "../../../src/concrete/deploy/StoxWrappedTokenVaultBeaconSetDeployer.sol";
import {
    StoxOffchainAssetReceiptVaultBeaconSetDeployer
} from "../../../src/concrete/deploy/StoxOffchainAssetReceiptVaultBeaconSetDeployer.sol";
import {
    StoxOffchainAssetReceiptVaultAuthorizerV1
} from "../../../src/concrete/authorize/StoxOffchainAssetReceiptVaultAuthorizerV1.sol";
import {
    StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1
} from "../../../src/concrete/authorize/StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1.sol";
import {StoxCorporateActionsFacet} from "../../../src/concrete/StoxCorporateActionsFacet.sol";
import {
    RUNTIME_CODE as STOX_RECEIPT_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_RECEIPT_GENERATED_ADDRESS
} from "../../../src/generated/StoxReceipt.pointers.sol";
import {
    RUNTIME_CODE as STOX_RECEIPT_VAULT_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_RECEIPT_VAULT_GENERATED_ADDRESS
} from "../../../src/generated/StoxReceiptVault.pointers.sol";
import {
    RUNTIME_CODE as STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_WRAPPED_TOKEN_VAULT_GENERATED_ADDRESS
} from "../../../src/generated/StoxWrappedTokenVault.pointers.sol";
import {
    RUNTIME_CODE as STOX_UNIFIED_DEPLOYER_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_UNIFIED_DEPLOYER_GENERATED_ADDRESS
} from "../../../src/generated/StoxUnifiedDeployer.pointers.sol";
import {
    RUNTIME_CODE as STOX_BEACON_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_BEACON_GENERATED_ADDRESS
} from "../../../src/generated/StoxWrappedTokenVaultBeacon.pointers.sol";
import {
    RUNTIME_CODE as STOX_BEACON_SET_DEPLOYER_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_BEACON_SET_DEPLOYER_GENERATED_ADDRESS
} from "../../../src/generated/StoxWrappedTokenVaultBeaconSetDeployer.pointers.sol";
import {
    RUNTIME_CODE as STOX_OARV_DEPLOYER_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_OARV_DEPLOYER_GENERATED_ADDRESS
} from "../../../src/generated/StoxOffchainAssetReceiptVaultBeaconSetDeployer.pointers.sol";
import {
    RUNTIME_CODE as STOX_AUTHORIZER_V1_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_AUTHORIZER_V1_GENERATED_ADDRESS
} from "../../../src/generated/StoxOffchainAssetReceiptVaultAuthorizerV1.pointers.sol";
import {
    RUNTIME_CODE as STOX_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_PAYMENT_MINT_AUTHORIZER_V1_GENERATED_ADDRESS
} from "../../../src/generated/StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1.pointers.sol";
import {
    RUNTIME_CODE as STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_CORPORATE_ACTIONS_FACET_GENERATED_ADDRESS
} from "../../../src/generated/StoxCorporateActionsFacet.pointers.sol";

/// @title LibProdDeployV4Test
/// @notice Pins every constant in `LibProdDeployV4` so a wrong address or
/// codehash literal fails a test. The lib's deployed-contract pins mirror the
/// `src/generated/*.pointers.sol` files (regenerated by `BuildPointers.sol`
/// against rain.vats 0.1.6) and reproduce as Zoltu-deterministic deployments,
/// so each contract is checked three ways:
///
/// 1. **Zoltu deploy** — deploy the fresh-compiled creation code through the
///    Zoltu factory and assert the deterministic address + runtime codehash
///    equal the V4 pins. Self-contained (no live fork, no pointer file): proves
///    the V4 pins match what the current source actually compiles + deploys to.
/// 2. **Pointer-address consistency** — the V4 address literal equals the
///    pointer file's `DEPLOYED_ADDRESS`. Pure, compile-independent.
/// 3. **Pointer-codehash consistency** — the V4 codehash literal equals
///    `keccak256(RUNTIME_CODE)` from the pointer file (the lib documents the
///    codehashes as exactly this). Pure, compile-independent.
///
/// The `STOX_PROD_AUTHORISER_V4_CLONE` pin is a non-deterministic deploy target
/// and is still an `address(0)` placeholder; `testAuthoriserV4ClonePlaceholder`
/// asserts that explicitly so the placeholder can't be silently shipped as a
/// real pin and so the test fails (prompting a real assertion) once the clone
/// is hydrated.
contract LibProdDeployV4Test is Test {
    // --- StoxReceipt ---

    function testDeployAddressStoxReceipt() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxReceipt).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_RECEIPT_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_RECEIPT_CODEHASH_RAIN_VATS_0_1_6);
    }

    function testGeneratedAddressStoxReceipt() external pure {
        assertEq(STOX_RECEIPT_GENERATED_ADDRESS, LibProdDeployV4.STOX_RECEIPT_RAIN_VATS_0_1_6);
    }

    function testCodehashMatchesPointerStoxReceipt() external pure {
        assertEq(LibProdDeployV4.STOX_RECEIPT_CODEHASH_RAIN_VATS_0_1_6, keccak256(STOX_RECEIPT_RUNTIME_CODE));
    }

    // --- StoxReceiptVault ---

    function testDeployAddressStoxReceiptVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxReceiptVault).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_RECEIPT_VAULT_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_RAIN_VATS_0_1_6);
    }

    function testGeneratedAddressStoxReceiptVault() external pure {
        assertEq(STOX_RECEIPT_VAULT_GENERATED_ADDRESS, LibProdDeployV4.STOX_RECEIPT_VAULT_RAIN_VATS_0_1_6);
    }

    function testCodehashMatchesPointerStoxReceiptVault() external pure {
        assertEq(
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_RAIN_VATS_0_1_6, keccak256(STOX_RECEIPT_VAULT_RUNTIME_CODE)
        );
    }

    // --- StoxWrappedTokenVault ---

    function testDeployAddressStoxWrappedTokenVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_RAIN_VATS_0_1_6);
    }

    function testGeneratedAddressStoxWrappedTokenVault() external pure {
        assertEq(STOX_WRAPPED_TOKEN_VAULT_GENERATED_ADDRESS, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RAIN_VATS_0_1_6);
    }

    function testCodehashMatchesPointerStoxWrappedTokenVault() external pure {
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_RAIN_VATS_0_1_6,
            keccak256(STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE)
        );
    }

    // --- StoxUnifiedDeployer ---

    function testDeployAddressStoxUnifiedDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxUnifiedDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6);
    }

    function testGeneratedAddressStoxUnifiedDeployer() external pure {
        assertEq(STOX_UNIFIED_DEPLOYER_GENERATED_ADDRESS, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RAIN_VATS_0_1_6);
    }

    function testCodehashMatchesPointerStoxUnifiedDeployer() external pure {
        assertEq(
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6,
            keccak256(STOX_UNIFIED_DEPLOYER_RUNTIME_CODE)
        );
    }

    // --- StoxWrappedTokenVaultBeacon (needs the wrapped token vault deployed first) ---

    function testDeployAddressStoxWrappedTokenVaultBeacon() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeacon).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_RAIN_VATS_0_1_6);
    }

    function testGeneratedAddressStoxWrappedTokenVaultBeacon() external pure {
        assertEq(STOX_BEACON_GENERATED_ADDRESS, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RAIN_VATS_0_1_6);
    }

    function testCodehashMatchesPointerStoxWrappedTokenVaultBeacon() external pure {
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_RAIN_VATS_0_1_6,
            keccak256(STOX_BEACON_RUNTIME_CODE)
        );
    }

    // --- StoxWrappedTokenVaultBeaconSetDeployer (needs vault + beacon first) ---

    function testDeployAddressStoxWrappedTokenVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeacon).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeaconSetDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(
            deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6
        );
    }

    function testGeneratedAddressStoxWrappedTokenVaultBeaconSetDeployer() external pure {
        assertEq(
            STOX_BEACON_SET_DEPLOYER_GENERATED_ADDRESS,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RAIN_VATS_0_1_6
        );
    }

    function testCodehashMatchesPointerStoxWrappedTokenVaultBeaconSetDeployer() external pure {
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6,
            keccak256(STOX_BEACON_SET_DEPLOYER_RUNTIME_CODE)
        );
    }

    // --- StoxOffchainAssetReceiptVaultBeaconSetDeployer (needs receipt + receipt vault first) ---

    function testDeployAddressStoxOffchainAssetReceiptVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxReceipt).creationCode);
        LibRainDeploy.deployZoltu(type(StoxReceiptVault).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultBeaconSetDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(
            deployed.codehash,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6
        );
    }

    function testGeneratedAddressStoxOffchainAssetReceiptVaultBeaconSetDeployer() external pure {
        assertEq(
            STOX_OARV_DEPLOYER_GENERATED_ADDRESS,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RAIN_VATS_0_1_6
        );
    }

    function testCodehashMatchesPointerStoxOffchainAssetReceiptVaultBeaconSetDeployer() external pure {
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_RAIN_VATS_0_1_6,
            keccak256(STOX_OARV_DEPLOYER_RUNTIME_CODE)
        );
    }

    // --- StoxOffchainAssetReceiptVaultAuthorizerV1 ---

    function testDeployAddressStoxOffchainAssetReceiptVaultAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultAuthorizerV1).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(
            deployed.codehash, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_RAIN_VATS_0_1_6
        );
    }

    function testGeneratedAddressStoxOffchainAssetReceiptVaultAuthorizerV1() external pure {
        assertEq(
            STOX_AUTHORIZER_V1_GENERATED_ADDRESS,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RAIN_VATS_0_1_6
        );
    }

    function testCodehashMatchesPointerStoxOffchainAssetReceiptVaultAuthorizerV1() external pure {
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_RAIN_VATS_0_1_6,
            keccak256(STOX_AUTHORIZER_V1_RUNTIME_CODE)
        );
    }

    // --- StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1 ---

    function testDeployAddressStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed =
            LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(
            deployed.codehash,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_RAIN_VATS_0_1_6
        );
    }

    function testGeneratedAddressStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external pure {
        assertEq(
            STOX_PAYMENT_MINT_AUTHORIZER_V1_GENERATED_ADDRESS,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RAIN_VATS_0_1_6
        );
    }

    function testCodehashMatchesPointerStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external pure {
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_RAIN_VATS_0_1_6,
            keccak256(STOX_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE)
        );
    }

    // --- StoxCorporateActionsFacet ---

    function testDeployAddressStoxCorporateActionsFacet() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxCorporateActionsFacet).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RAIN_VATS_0_1_6);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_RAIN_VATS_0_1_6);
    }

    function testGeneratedAddressStoxCorporateActionsFacet() external pure {
        assertEq(
            STOX_CORPORATE_ACTIONS_FACET_GENERATED_ADDRESS, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RAIN_VATS_0_1_6
        );
    }

    function testCodehashMatchesPointerStoxCorporateActionsFacet() external pure {
        assertEq(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_RAIN_VATS_0_1_6,
            keccak256(STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE)
        );
    }

    // --- Non-deployed-contract constants ---

    /// The beacon initial owner is rainlang.eth and unchanged across versions.
    function testBeaconInitialOwner() external pure {
        assertEq(LibProdDeployV4.BEACON_INITIAL_OWNER, address(0x8E4bdeec7CEB9570D440676345dA1dCe10329f5b));
    }

    /// The rain.vats tag string is encoded into every deployed-contract
    /// constant name, so it must match the `_RAIN_VATS_0_1_6` suffix used
    /// throughout the lib.
    function testRainVatsTag() external pure {
        assertEq(LibProdDeployV4.RAIN_VATS_TAG, "RAIN_VATS_0_1_6");
    }

    /// The V4 authoriser clone ADDRESS is a non-deterministic deploy target
    /// and is still a placeholder. Asserting the placeholder explicitly
    /// prevents it from being silently shipped as a real pin, and makes
    /// this test fail (prompting a real address assertion) the moment the
    /// clone is hydrated with its deployed literal.
    function testAuthoriserV4ClonePlaceholder() external pure {
        assertEq(
            LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE,
            address(0),
            "clone hydrated: replace this placeholder guard with a real address assertion"
        );
    }

    /// The V4 authoriser clone CODEHASH is deterministic ahead of the deploy
    /// — the EIP-1167 runtime with the pinned V4 impl address embedded — so
    /// unlike the address it is hydrated before the broadcast. Re-derive it
    /// from the impl pin and assert the literal matches, so an impl-address
    /// change can't leave a stale codehash behind.
    function testAuthoriserV4CloneCodehashMatchesImplDerivation() external pure {
        bytes32 derived = keccak256(
            abi.encodePacked(
                hex"363d3d373d3d3d363d73",
                LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RAIN_VATS_0_1_6,
                hex"5af43d82803e903d91602b57fd5bf3"
            )
        );
        assertEq(
            LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH,
            derived,
            "clone codehash literal drifted from the EIP-1167(impl) derivation"
        );
    }
}
