// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {LibRainDeploy} from "rain-deploy-0.1.4/src/lib/LibRainDeploy.sol";
import {ERC1167_PREFIX, ERC1167_SUFFIX} from "rain-extrospection-0.1.1/src/lib/LibExtrospectERC1167Proxy.sol";
import {LibProdDeployV4} from "../../../src/lib/LibProdDeployV4.sol";
import {StoxReceipt} from "../../../src/concrete/StoxReceipt.sol";
import {StoxReceiptVault} from "../../../src/concrete/StoxReceiptVault.sol";
import {StoxWrappedTokenVault} from "../../../src/concrete/StoxWrappedTokenVault.sol";
import {StoxUnifiedDeployer} from "../../../src/concrete/deploy/StoxUnifiedDeployer.sol";
import {StoxWrappedTokenVaultBeacon} from "../../../src/concrete/StoxWrappedTokenVaultBeacon.sol";
import {
    StoxWrappedTokenVaultBeaconSetDeployer
} from "../../../src/concrete/deploy/StoxWrappedTokenVaultBeaconSetDeployer.sol";
import {
    StoxOffchainAssetReceiptVaultBeaconSetDeployer
} from "../../../src/concrete/deploy/StoxOffchainAssetReceiptVaultBeaconSetDeployer.sol";
import {
    StoxOffchainAssetReceiptVaultAuthorizerV1
} from "../../../src/concrete/authorize/StoxOffchainAssetReceiptVaultAuthorizerV1.sol";
import {
    StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1
} from "../../../src/concrete/authorize/StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1.sol";
import {StoxCorporateActionsFacet} from "../../../src/concrete/StoxCorporateActionsFacet.sol";
import {ST0xOrchestrator} from "../../../src/concrete/ST0xOrchestrator.sol";
import {ST0xOrchestratorBeaconSetDeployer} from "../../../src/concrete/deploy/ST0xOrchestratorBeaconSetDeployer.sol";
import {
    RUNTIME_CODE as STOX_RECEIPT_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_RECEIPT_GENERATED_ADDRESS
} from "../../../src/generated/StoxReceipt.pointers.sol";
import {
    RUNTIME_CODE as STOX_RECEIPT_VAULT_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_RECEIPT_VAULT_GENERATED_ADDRESS
} from "../../../src/generated/StoxReceiptVault.pointers.sol";
import {
    RUNTIME_CODE as STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_WRAPPED_TOKEN_VAULT_GENERATED_ADDRESS
} from "../../../src/generated/StoxWrappedTokenVault.pointers.sol";
import {
    RUNTIME_CODE as STOX_UNIFIED_DEPLOYER_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_UNIFIED_DEPLOYER_GENERATED_ADDRESS
} from "../../../src/generated/StoxUnifiedDeployer.pointers.sol";
import {
    RUNTIME_CODE as STOX_BEACON_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_BEACON_GENERATED_ADDRESS
} from "../../../src/generated/StoxWrappedTokenVaultBeacon.pointers.sol";
import {
    RUNTIME_CODE as STOX_BEACON_SET_DEPLOYER_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_BEACON_SET_DEPLOYER_GENERATED_ADDRESS
} from "../../../src/generated/StoxWrappedTokenVaultBeaconSetDeployer.pointers.sol";
import {
    RUNTIME_CODE as STOX_OARV_DEPLOYER_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_OARV_DEPLOYER_GENERATED_ADDRESS
} from "../../../src/generated/StoxOffchainAssetReceiptVaultBeaconSetDeployer.pointers.sol";
import {
    RUNTIME_CODE as STOX_AUTHORIZER_V1_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_AUTHORIZER_V1_GENERATED_ADDRESS
} from "../../../src/generated/StoxOffchainAssetReceiptVaultAuthorizerV1.pointers.sol";
import {
    RUNTIME_CODE as STOX_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_PAYMENT_MINT_AUTHORIZER_V1_GENERATED_ADDRESS
} from "../../../src/generated/StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1.pointers.sol";
import {
    RUNTIME_CODE as STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE,
    DEPLOYED_ADDRESS as STOX_CORPORATE_ACTIONS_FACET_GENERATED_ADDRESS
} from "../../../src/generated/StoxCorporateActionsFacet.pointers.sol";
import {
    RUNTIME_CODE as ST0X_ORCHESTRATOR_RUNTIME_CODE,
    DEPLOYED_ADDRESS as ST0X_ORCHESTRATOR_GENERATED_ADDRESS
} from "../../../src/generated/ST0xOrchestrator.pointers.sol";
import {
    RUNTIME_CODE as ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE,
    DEPLOYED_ADDRESS as ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_GENERATED_ADDRESS
} from "../../../src/generated/ST0xOrchestratorBeaconSetDeployer.pointers.sol";

/// @title LibProdDeployV4Test
/// @notice Pins every constant in `LibProdDeployV4` so a wrong address or
/// codehash literal fails a test. The lib's deployed-contract pins mirror the
/// `src/generated/*.pointers.sol` files (regenerated by `BuildPointers.sol`
/// against rain.vats 0.1.6) and reproduce as Zoltu-deterministic deployments,
/// so each contract is checked three ways:
///
/// 1. **Zoltu deploy** — deploy the fresh-compiled creation code through the
///    Zoltu factory and assert the deterministic address + runtime codehash
///    equal the V4 pins. Self-contained (no live fork, no pointer file): proves
///    the V4 pins match what the current source actually compiles + deploys to.
/// 2. **Pointer-address consistency** — the V4 address literal equals the
///    pointer file's `DEPLOYED_ADDRESS`. Pure, compile-independent.
/// 3. **Pointer-codehash consistency** — the V4 codehash literal equals
///    `keccak256(RUNTIME_CODE)` from the pointer file (the lib documents the
///    codehashes as exactly this). Pure, compile-independent.
///
/// The `STOX_PROD_AUTHORISER_V4_CLONE` pin is a non-deterministic deploy target
/// and is still an `address(0)` placeholder; `testAuthoriserV4ClonePlaceholder`
/// asserts that explicitly so the placeholder can't be silently shipped as a
/// real pin and so the test fails (prompting a real assertion) once the clone
/// is hydrated.
contract LibProdDeployV4Test is Test {
    // --- StoxReceipt ---

    function testDeployAddressStoxReceipt() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxReceipt).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_RECEIPT_0_1_1);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_1);
    }

    function testGeneratedAddressStoxReceipt() external pure {
        assertEq(STOX_RECEIPT_GENERATED_ADDRESS, LibProdDeployV4.STOX_RECEIPT_0_1_1);
    }

    function testCodehashMatchesPointerStoxReceipt() external pure {
        assertEq(LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_1, keccak256(STOX_RECEIPT_RUNTIME_CODE));
    }

    // --- StoxReceiptVault (0.1.3 — rebuilt: its `fallback()` hardcodes the
    // rebuilt 0.1.3 corporate-actions facet, so the current source and the
    // top-level generated pointer compile to the 0.1.3 vault). ---

    function testDeployAddressStoxReceiptVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxReceiptVault).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_3);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_3);
    }

    function testGeneratedAddressStoxReceiptVault() external pure {
        assertEq(STOX_RECEIPT_VAULT_GENERATED_ADDRESS, LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_3);
    }

    function testCodehashMatchesPointerStoxReceiptVault() external pure {
        assertEq(LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_3, keccak256(STOX_RECEIPT_VAULT_RUNTIME_CODE));
    }

    // --- StoxWrappedTokenVault ---

    function testDeployAddressStoxWrappedTokenVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_0_1_1);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_1);
    }

    function testGeneratedAddressStoxWrappedTokenVault() external pure {
        assertEq(STOX_WRAPPED_TOKEN_VAULT_GENERATED_ADDRESS, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_0_1_1);
    }

    function testCodehashMatchesPointerStoxWrappedTokenVault() external pure {
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_1, keccak256(STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE)
        );
    }

    // --- StoxUnifiedDeployer (0.1.3 — rebuilt: it embeds the rebuilt 0.1.3
    // OARV beacon-set deployer address, so the current source and the top-level
    // generated pointer compile to the 0.1.3 unified deployer). ---

    function testDeployAddressStoxUnifiedDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxUnifiedDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_3);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_3);
    }

    function testGeneratedAddressStoxUnifiedDeployer() external pure {
        assertEq(STOX_UNIFIED_DEPLOYER_GENERATED_ADDRESS, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_3);
    }

    function testCodehashMatchesPointerStoxUnifiedDeployer() external pure {
        assertEq(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_3, keccak256(STOX_UNIFIED_DEPLOYER_RUNTIME_CODE));
    }

    // --- StoxWrappedTokenVaultBeacon (needs the wrapped token vault deployed first) ---

    function testDeployAddressStoxWrappedTokenVaultBeacon() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeacon).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_0_1_1);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_1);
    }

    function testGeneratedAddressStoxWrappedTokenVaultBeacon() external pure {
        assertEq(STOX_BEACON_GENERATED_ADDRESS, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_0_1_1);
    }

    function testCodehashMatchesPointerStoxWrappedTokenVaultBeacon() external pure {
        assertEq(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_1, keccak256(STOX_BEACON_RUNTIME_CODE));
    }

    // --- StoxWrappedTokenVaultBeaconSetDeployer (0.1.3 — a mover: its
    // `supportsInterface` inherits OpenZeppelin `ERC165` and chains `super`, so
    // its bytecode differs from the byte-identical 0.1.2 twin and the current
    // source and the top-level generated pointer compile to the 0.1.3 deployer.
    // Needs vault + beacon first). ---

    function testDeployAddressStoxWrappedTokenVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeacon).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeaconSetDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_3);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3);
    }

    function testGeneratedAddressStoxWrappedTokenVaultBeaconSetDeployer() external pure {
        assertEq(
            STOX_BEACON_SET_DEPLOYER_GENERATED_ADDRESS,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_3
        );
    }

    function testCodehashMatchesPointerStoxWrappedTokenVaultBeaconSetDeployer() external pure {
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3,
            keccak256(STOX_BEACON_SET_DEPLOYER_RUNTIME_CODE)
        );
    }

    // --- StoxOffchainAssetReceiptVaultBeaconSetDeployer (0.1.3 — rebuilt: its
    // constructor bakes a beacon over the rebuilt 0.1.3 receipt-vault impl, so
    // the current source and the top-level generated pointer compile to the
    // 0.1.3 deployer. Needs receipt + the 0.1.3 receipt vault deployed first so
    // the beacon's impl-has-code check passes). ---

    function testDeployAddressStoxOffchainAssetReceiptVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxReceipt).creationCode);
        LibRainDeploy.deployZoltu(type(StoxReceiptVault).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultBeaconSetDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_3);
        assertTrue(deployed.code.length > 0);
        assertEq(
            deployed.codehash, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
        );
    }

    function testGeneratedAddressStoxOffchainAssetReceiptVaultBeaconSetDeployer() external pure {
        assertEq(
            STOX_OARV_DEPLOYER_GENERATED_ADDRESS,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_3
        );
    }

    function testCodehashMatchesPointerStoxOffchainAssetReceiptVaultBeaconSetDeployer() external pure {
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3,
            keccak256(STOX_OARV_DEPLOYER_RUNTIME_CODE)
        );
    }

    // --- StoxOffchainAssetReceiptVaultAuthorizerV1 ---

    function testDeployAddressStoxOffchainAssetReceiptVaultAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultAuthorizerV1).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_1);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_1);
    }

    function testGeneratedAddressStoxOffchainAssetReceiptVaultAuthorizerV1() external pure {
        assertEq(
            STOX_AUTHORIZER_V1_GENERATED_ADDRESS, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_1
        );
    }

    function testCodehashMatchesPointerStoxOffchainAssetReceiptVaultAuthorizerV1() external pure {
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_1,
            keccak256(STOX_AUTHORIZER_V1_RUNTIME_CODE)
        );
    }

    // --- StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1 ---

    function testDeployAddressStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed =
            LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_0_1_1);
        assertTrue(deployed.code.length > 0);
        assertEq(
            deployed.codehash,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
    }

    function testGeneratedAddressStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external pure {
        assertEq(
            STOX_PAYMENT_MINT_AUTHORIZER_V1_GENERATED_ADDRESS,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_0_1_1
        );
    }

    function testCodehashMatchesPointerStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external pure {
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_1,
            keccak256(STOX_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE)
        );
    }

    // --- StoxCorporateActionsFacet (0.1.3 — rebuilt for the
    // cumulative-multiplier change; the current source and the top-level
    // generated pointer now compile to the 0.1.3 facet, so these current-source
    // trios pin the `_0_1_3` facet). ---

    function testDeployAddressStoxCorporateActionsFacet() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxCorporateActionsFacet).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_3);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_3);
    }

    function testGeneratedAddressStoxCorporateActionsFacet() external pure {
        assertEq(STOX_CORPORATE_ACTIONS_FACET_GENERATED_ADDRESS, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_3);
    }

    function testCodehashMatchesPointerStoxCorporateActionsFacet() external pure {
        assertEq(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_3,
            keccak256(STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE)
        );
    }

    // --- ST0xOrchestrator (0.1.3 — rebuilt: it embeds the rebuilt 0.1.3 OARV
    // beacon-set deployer and receipt-vault addresses, so the current source
    // and the top-level generated pointer compile to the 0.1.3 orchestrator). ---

    function testDeployAddressST0xOrchestrator() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(ST0xOrchestrator).creationCode);
        assertEq(deployed, LibProdDeployV4.ST0X_ORCHESTRATOR_0_1_3);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_3);
    }

    function testGeneratedAddressST0xOrchestrator() external pure {
        assertEq(ST0X_ORCHESTRATOR_GENERATED_ADDRESS, LibProdDeployV4.ST0X_ORCHESTRATOR_0_1_3);
    }

    function testCodehashMatchesPointerST0xOrchestrator() external pure {
        assertEq(LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_3, keccak256(ST0X_ORCHESTRATOR_RUNTIME_CODE));
    }

    // --- ST0xOrchestratorBeaconSetDeployer (0.1.3 — rebuilt: its constructor
    // bakes a beacon over the rebuilt 0.1.3 orchestrator impl, so the current
    // source and the top-level generated pointer compile to the 0.1.3 deployer.
    // Needs the 0.1.3 orchestrator impl deployed first so the beacon's
    // impl-has-code check passes). ---

    function testDeployAddressST0xOrchestratorBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(ST0xOrchestrator).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(ST0xOrchestratorBeaconSetDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_0_1_3);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_3);
    }

    function testGeneratedAddressST0xOrchestratorBeaconSetDeployer() external pure {
        assertEq(
            ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_GENERATED_ADDRESS,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_0_1_3
        );
    }

    function testCodehashMatchesPointerST0xOrchestratorBeaconSetDeployer() external pure {
        assertEq(
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_3,
            keccak256(ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE)
        );
    }

    // --- Non-deployed-contract constants ---

    /// The beacon initial owner is rainlang.eth and unchanged across versions.
    function testBeaconInitialOwner() external pure {
        assertEq(LibProdDeployV4.BEACON_INITIAL_OWNER, address(0x8E4bdeec7CEB9570D440676345dA1dCe10329f5b));
    }

    /// The deploy tag string is encoded into every current-release
    /// deployed-contract constant name, so it must match the `_0_1_3` suffix.
    function testDeployTag() external pure {
        assertEq(LibProdDeployV4.DEPLOY_TAG, "0_1_3");
    }

    /// The V4 authoriser clone ADDRESS is a non-deterministic deploy target
    /// and is still a placeholder. Asserting the placeholder explicitly
    /// prevents it from being silently shipped as a real pin, and makes
    /// this test fail (prompting a real address assertion) the moment the
    /// clone is hydrated with its deployed literal.
    function testAuthoriserV4ClonePlaceholder() external pure {
        assertEq(
            LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE,
            address(0),
            "clone hydrated: replace this placeholder guard with a real address assertion"
        );
    }

    /// The V4 authoriser clone CODEHASH is deterministic ahead of the deploy
    /// — the EIP-1167 runtime with the pinned V4 impl address embedded — so
    /// unlike the address it is hydrated before the broadcast. Re-derive it
    /// from the impl pin and assert the literal matches, so an impl-address
    /// change can't leave a stale codehash behind.
    function testAuthoriserV4CloneCodehashMatchesImplDerivation() external pure {
        bytes32 derived = keccak256(
            abi.encodePacked(
                ERC1167_PREFIX,
                LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_1,
                ERC1167_SUFFIX
            )
        );
        assertEq(
            LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH,
            derived,
            "clone codehash literal drifted from the EIP-1167(impl) derivation"
        );
    }

    /// st0x-deploy 0.1.2 re-pins the ten 0.1.1 contracts at IDENTICAL values
    /// (only the orchestrator + its deployer are new to 0.1.2), so every 0.1.2
    /// twin must equal its 0.1.1 counterpart. The 0.1.1 trios above already
    /// prove each 0.1.1 value against its generated pointer, so proving the
    /// twins equal 0.1.1 carries that pointer-consistency over to 0.1.2 — and
    /// fails the moment a twin is edited to drift.
    function testRelease012TwinsEqualRelease011() external pure {
        assertEq(LibProdDeployV4.STOX_RECEIPT_0_1_2, LibProdDeployV4.STOX_RECEIPT_0_1_1);
        assertEq(LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_2, LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_1);
        assertEq(LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_2, LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_1);
        assertEq(LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_2, LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_1);
        assertEq(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_0_1_2, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_0_1_1);
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_2,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_1
        );
        assertEq(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_2, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_1);
        assertEq(
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_2, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_0_1_2, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_2,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_2,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_2,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_2,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_2,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_2,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_2,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_0_1_2,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_0_1_1
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_2,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
        assertEq(LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_2, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_1);
        assertEq(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_2,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_1
        );
    }

    /// st0x-deploy 0.1.3 re-pins FIVE of the twelve 0.1.2 contracts at IDENTICAL
    /// values and rebuilds the other SEVEN. Two source changes drive the
    /// rebuilds. `StoxCorporateActionsFacet` changed at the source (the
    /// cumulative-multiplier change); the receipt vault hardcodes that facet in
    /// its `fallback()` and each downstream deployer/orchestrator embeds a
    /// rebuilt address, so the change cascades — the receipt vault, the OARV
    /// beacon-set deployer, the unified deployer, the orchestrator, and the
    /// orchestrator beacon-set deployer each get a new Zoltu address + codehash.
    /// An ERC-165 fix changed the `supportsInterface` bytecode of the unified
    /// deployer, the wrapped-token-vault beacon-set deployer, and the
    /// orchestrator directly — moving the wrapped-token-vault beacon-set deployer
    /// too (the other two already move with the facet cascade).
    /// Every 0.1.3 twin below must equal its 0.1.2 counterpart, and every 0.1.3
    /// mover must NOT equal it. The 0.1.2 trios/twins above already prove each
    /// 0.1.2 value against its generated pointer / 0.1.1 twin, so proving the
    /// 0.1.3 twins equal 0.1.2 carries that consistency over to 0.1.3 — and the
    /// mover not-equal assertions fail the moment a mover is reverted to a twin
    /// (or a twin drifts).
    function testRelease013TwinsEqualRelease012() external pure {
        // --- The five byte-identical 0.1.2 twins. ---
        assertEq(LibProdDeployV4.STOX_RECEIPT_0_1_3, LibProdDeployV4.STOX_RECEIPT_0_1_2);
        assertEq(LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_3, LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_2);
        assertEq(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_0_1_3, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_0_1_2);
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_3,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_2
        );
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_0_1_3, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_0_1_2
        );
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_3,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_2
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_3,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_2
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_3,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_2
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_0_1_3,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_0_1_2
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_3,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_2
        );

        // --- The seven 0.1.3 movers: each MUST differ from its 0.1.2 pin. A
        // mover reverted to its 0.1.2 twin (or a rebuild dropped) trips this. ---
        assertTrue(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_3
                != LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_2
        );
        assertTrue(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
                != LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_2
        );
        assertTrue(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_3 != LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_2
        );
        assertTrue(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_3
                != LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_2
        );
        assertTrue(LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_3 != LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_2);
        assertTrue(
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_3 != LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_2
        );
        assertTrue(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_3
                != LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_2
        );
        assertTrue(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
                != LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_2
        );
        assertTrue(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_3 != LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_2);
        assertTrue(
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_3 != LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_2
        );
        assertTrue(LibProdDeployV4.ST0X_ORCHESTRATOR_0_1_3 != LibProdDeployV4.ST0X_ORCHESTRATOR_0_1_2);
        assertTrue(LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_3 != LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_2);
        assertTrue(
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_0_1_3
                != LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_0_1_2
        );
        assertTrue(
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
                != LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_2
        );
    }

    /// Each release's frozen runtime bytecode hashes to that release's codehash
    /// pin — proving the per-tag bytecode record is self-consistent (and, for
    /// 0.1.1, that the frozen snapshot matches the codehash independent of the
    /// current build).
    function testTaggedRuntimeHashesToCodehash() external pure {
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_0_1_1), LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_0_1_2), LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.ST0X_ORCHESTRATOR_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_2),
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_2
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_0_1_3), LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.ST0X_ORCHESTRATOR_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_3
        );
        assertEq(
            keccak256(LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_3),
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
        );
    }

    // =========================================================================
    // Frozen-record redeploy reproducibility (no fork).
    //
    // Deploying the FROZEN per-release creation bytecode — the historical
    // `X_CREATION_CODE_<tag>` record in `LibProdDeployV4`, NOT the current
    // source's `type(X).creationCode` — back through the Zoltu factory lands at
    // the frozen `X_<tag>` address holding the frozen `X_RUNTIME_CODE_<tag>`
    // bytecode with the frozen `X_CODEHASH_<tag>`. This proves the release is
    // reproducible from the pinned constants alone: given only the frozen
    // record, the same runtime redeploys to the same address even after the
    // current source diverges. The `testDeployAddress*` tests above instead
    // deploy the CURRENT source and are what break when the source drifts; these
    // pin the frozen bytecode itself.
    //
    // Only DISTINCT (creation code, address) pairs are covered: the ten 0.1.1
    // contracts plus the two 0.1.2-only contracts (the orchestrator and its
    // deployer). The 0.1.2 twins of the ten are byte-identical creation code, so
    // they Zoltu-derive the SAME address (already proven equal by
    // `testRelease012TwinsEqualRelease011`) and redeploying them would collide
    // on the already-occupied address.
    //
    // Deployer dependency ordering mirrors the `testDeployAddress*` tests
    // exactly: a deployer/beacon whose constructor bakes an impl address needs
    // that impl deployed first, so each such test first deploys the impl(s)'
    // FROZEN creation code (which lands at the same frozen Zoltu address the
    // constructor bakes) before deploying the target.
    // =========================================================================

    /// Deploys `creationCode` through the Zoltu factory and asserts the deploy
    /// reproduces the frozen address, full runtime bytecode, and codehash.
    function _assertFrozenRedeploy(
        bytes memory creationCode,
        address expectedAddress,
        bytes memory expectedRuntimeCode,
        bytes32 expectedCodehash
    ) internal {
        address deployed = LibRainDeploy.deployZoltu(creationCode);
        assertEq(deployed, expectedAddress);
        assertEq(deployed.code, expectedRuntimeCode);
        assertEq(deployed.codehash, expectedCodehash);
    }

    // --- 0.1.1 frozen redeploys ---

    function testFrozenRedeployStoxReceipt() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxReceiptVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxWrappedTokenVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxUnifiedDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_1,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_1
        );
    }

    /// The beacon's `UpgradeableBeacon` constructor validates its impl has code,
    /// so the wrapped-token-vault impl is deployed (frozen) first.
    function testFrozenRedeployStoxWrappedTokenVaultBeacon() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CREATION_CODE_0_1_1);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_1
        );
    }

    /// Needs the wrapped-token-vault impl and its beacon deployed (frozen)
    /// first, matching `testDeployAddressStoxWrappedTokenVaultBeaconSetDeployer`.
    function testFrozenRedeployStoxWrappedTokenVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CREATION_CODE_0_1_1);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CREATION_CODE_0_1_1);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
    }

    /// Its constructor builds two beacons over the receipt and receipt-vault
    /// impls, so both are deployed (frozen) first, matching
    /// `testDeployAddressStoxOffchainAssetReceiptVaultBeaconSetDeployer`.
    function testFrozenRedeployStoxOffchainAssetReceiptVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_0_1_1);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_0_1_1);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxOffchainAssetReceiptVaultAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxCorporateActionsFacet() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_1,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_1
        );
    }

    // --- 0.1.2-only frozen redeploys (new to the 0.1.2 release) ---

    function testFrozenRedeployST0xOrchestrator() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_0_1_2,
            LibProdDeployV4.ST0X_ORCHESTRATOR_0_1_2,
            LibProdDeployV4.ST0X_ORCHESTRATOR_RUNTIME_CODE_0_1_2,
            LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_2
        );
    }

    /// Its constructor builds an `UpgradeableBeacon` over the orchestrator impl,
    /// so the impl is deployed (frozen) first, matching
    /// `testDeployAddressST0xOrchestratorBeaconSetDeployer`.
    function testFrozenRedeployST0xOrchestratorBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_0_1_2);
        _assertFrozenRedeploy(
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_2,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_0_1_2,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_2,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_2
        );
    }

    // --- 0.1.3 movers' frozen redeploys (seven contracts are rebuilt in 0.1.3:
    // the corporate-actions facet plus the receipt vault, OARV beacon-set
    // deployer, unified deployer, orchestrator, and orchestrator beacon-set
    // deployer that cascade from it, and the wrapped-token-vault beacon-set
    // deployer moved by the ERC-165 `supportsInterface` fix; the other five are
    // byte-identical 0.1.2 twins that Zoltu-derive the already-occupied 0.1.2
    // addresses, so only these seven have a distinct (creation code, address)
    // pair to redeploy). Deployer/beacon dependency ordering mirrors the
    // `testDeployAddress*` tests exactly: an impl a constructor bakes is deployed
    // (frozen, at its 0.1.3 address) first. ---

    /// Standalone (its constructor is empty — the beacon is referenced only at
    /// call time), so no impl predeploy is needed. It moves in 0.1.3 for the
    /// ERC-165 `supportsInterface` change, not the facet cascade.
    function testFrozenRedeployStoxWrappedTokenVaultBeaconSetDeployer_0_1_3() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_3,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_3,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_3,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
        );
    }

    function testFrozenRedeployStoxCorporateActionsFacet_0_1_3() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CREATION_CODE_0_1_3,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_3,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_3,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_3
        );
    }

    function testFrozenRedeployStoxReceiptVault_0_1_3() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_0_1_3,
            LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_3,
            LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_3,
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_3
        );
    }

    /// Its constructor builds two beacons over the receipt and receipt-vault
    /// impls, so both are deployed (frozen, at their 0.1.3 addresses) first.
    function testFrozenRedeployStoxOffchainAssetReceiptVaultBeaconSetDeployer_0_1_3() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_0_1_3);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_0_1_3);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_3,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_3,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_3,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
        );
    }

    function testFrozenRedeployStoxUnifiedDeployer_0_1_3() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CREATION_CODE_0_1_3,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_3,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_0_1_3,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_3
        );
    }

    function testFrozenRedeployST0xOrchestrator_0_1_3() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_0_1_3,
            LibProdDeployV4.ST0X_ORCHESTRATOR_0_1_3,
            LibProdDeployV4.ST0X_ORCHESTRATOR_RUNTIME_CODE_0_1_3,
            LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_3
        );
    }

    /// Its constructor builds an `UpgradeableBeacon` over the orchestrator impl,
    /// so the impl is deployed (frozen, at its 0.1.3 address) first.
    function testFrozenRedeployST0xOrchestratorBeaconSetDeployer_0_1_3() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_0_1_3);
        _assertFrozenRedeploy(
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_3,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_0_1_3,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_3,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_3
        );
    }
}
