// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.2/src/Test.sol";
import {LibRainDeploy} from "rain-deploy-0.1.10/src/lib/LibRainDeploy.sol";
import {ERC1167_PREFIX, ERC1167_SUFFIX} from "rain-extrospection-0.1.14/src/lib/LibExtrospectERC1167Proxy.sol";
import {LibProdDeployV4} from "../../../src/generated/LibProdDeployV4.sol";
import {LibProdDeployCurrent} from "../../../src/generated/LibProdDeployCurrent.sol";
import {StoxReceipt} from "../../../src/concrete/StoxReceipt.sol";
import {StoxReceiptVault} from "../../../src/concrete/StoxReceiptVault.sol";
import {StoxWrappedTokenVault} from "../../../src/concrete/StoxWrappedTokenVault.sol";
import {StoxUnifiedDeployer} from "../../../src/concrete/deploy/StoxUnifiedDeployer.sol";
import {StoxWrappedTokenVaultBeacon} from "../../../src/concrete/StoxWrappedTokenVaultBeacon.sol";
import {
    StoxWrappedTokenVaultBeaconSetDeployer
} from "../../../src/concrete/deploy/StoxWrappedTokenVaultBeaconSetDeployer.sol";
import {
    StoxOffchainAssetReceiptVaultBeaconSetDeployer
} from "../../../src/concrete/deploy/StoxOffchainAssetReceiptVaultBeaconSetDeployer.sol";
import {
    StoxOffchainAssetReceiptVaultAuthorizerV1
} from "../../../src/concrete/authorize/StoxOffchainAssetReceiptVaultAuthorizerV1.sol";
import {
    StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1
} from "../../../src/concrete/authorize/StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1.sol";
import {StoxCorporateActionsFacet} from "../../../src/concrete/StoxCorporateActionsFacet.sol";
import {ST0xOrchestrator} from "../../../src/concrete/ST0xOrchestrator.sol";
import {ST0xOrchestratorBeaconSetDeployer} from "../../../src/concrete/deploy/ST0xOrchestratorBeaconSetDeployer.sol";
import {St0xAttestSubParser} from "../../../src/concrete/St0xAttestSubParser.sol";

/// @title LibProdDeployV4Test
/// @notice Pins every constant in `LibProdDeployV4` so a wrong address or
/// codehash fails a test. Each deployed-contract constant is an alias of the
/// frozen `src/generated/<tag>/` snapshot (its `DEPLOYED_ADDRESS` /
/// `BYTECODE_HASH`) generated by `BuildPointers.sol`:
///
/// 1. **Zoltu deploy** — deploy through the Zoltu factory and assert the
///    deterministic address + runtime codehash equal the pins (no live fork).
///    `testDeployAddress*` deploys the current source's creation code;
///    `testFrozenRedeploy*` redeploys the tag's frozen snapshot `CREATION_CODE`.
/// 2. **Tagged codehash consistency** (`testTaggedRuntimeHashesToCodehash`) —
///    per tag, `keccak256(RUNTIME_CODE_<tag>) == CODEHASH_<tag>`.
/// 3. **Twin equality** (`testRelease*TwinsEqual*`) — a contract unchanged
///    across a release has byte-identical pins in both tags.
///
/// `STOX_PROD_AUTHORISER_V4_CLONE` is a non-deterministic deploy target;
/// `testAuthoriserV4ClonePin` asserts the literal and the codehash derivation.
contract LibProdDeployV4Test is Test {
    // --- StoxReceipt ---

    function testDeployAddressStoxReceipt() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxReceipt).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_RECEIPT_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_RECEIPT_CODEHASH_CANDIDATE);
    }

    // --- StoxReceiptVault (its `fallback()` hardcodes the candidate
    // corporate-actions facet, so the current source compiles to the candidate vault). ---

    function testDeployAddressStoxReceiptVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxReceiptVault).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_RECEIPT_VAULT_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_CANDIDATE);
    }

    // --- StoxWrappedTokenVault ---

    function testDeployAddressStoxWrappedTokenVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_CANDIDATE);
    }

    // --- StoxUnifiedDeployer (embeds the candidate OARV beacon-set deployer
    // address, so the current source compiles to the candidate unified deployer). ---

    function testDeployAddressStoxUnifiedDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxUnifiedDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_CANDIDATE);
    }

    // --- StoxWrappedTokenVaultBeacon (needs the wrapped token vault deployed first) ---

    function testDeployAddressStoxWrappedTokenVaultBeacon() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeacon).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_CANDIDATE);
    }

    // --- StoxWrappedTokenVaultBeaconSetDeployer (its `supportsInterface`
    // inherits OpenZeppelin `ERC165` and chains `super`, so its bytecode differs
    // from the 0.1.1 deployer and the current source compiles to the candidate
    // deployer. Needs vault + beacon first). ---

    function testDeployAddressStoxWrappedTokenVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVault).creationCode);
        LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeacon).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxWrappedTokenVaultBeaconSetDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE);
    }

    // --- StoxOffchainAssetReceiptVaultBeaconSetDeployer (its constructor bakes
    // a beacon over the candidate receipt-vault impl, so the current source
    // compiles to the candidate deployer. Needs receipt + the candidate receipt
    // vault deployed first so the beacon's impl-has-code check passes). ---

    function testDeployAddressStoxOffchainAssetReceiptVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(StoxReceipt).creationCode);
        LibRainDeploy.deployZoltu(type(StoxReceiptVault).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultBeaconSetDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(
            deployed.codehash, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE
        );
    }

    // --- StoxOffchainAssetReceiptVaultAuthorizerV1 ---

    function testDeployAddressStoxOffchainAssetReceiptVaultAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultAuthorizerV1).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_CANDIDATE);
    }

    // --- StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1 ---

    function testDeployAddressStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed =
            LibRainDeploy.deployZoltu(type(StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(
            deployed.codehash,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_CANDIDATE
        );
    }

    // --- StoxCorporateActionsFacet (the current source compiles to the
    // candidate facet, so these trios pin the `_CANDIDATE` facet). ---

    function testDeployAddressStoxCorporateActionsFacet() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(StoxCorporateActionsFacet).creationCode);
        assertEq(deployed, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_CANDIDATE);
    }

    // --- ST0xOrchestrator (embeds the candidate OARV beacon-set deployer and
    // receipt-vault addresses, so the current source compiles to the candidate
    // orchestrator). ---

    function testDeployAddressST0xOrchestrator() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(ST0xOrchestrator).creationCode);
        assertEq(deployed, LibProdDeployV4.ST0X_ORCHESTRATOR_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_CANDIDATE);
    }

    // --- ST0xOrchestratorBeaconSetDeployer (its constructor bakes a beacon
    // over the candidate orchestrator impl, so the current source compiles to
    // the candidate deployer. Needs the candidate orchestrator impl deployed
    // first so the beacon's impl-has-code check passes). ---

    function testDeployAddressST0xOrchestratorBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(type(ST0xOrchestrator).creationCode);
        address deployed = LibRainDeploy.deployZoltu(type(ST0xOrchestratorBeaconSetDeployer).creationCode);
        assertEq(deployed, LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE);
    }

    function testDeployAddressSt0xAttestSubParser() external {
        LibRainDeploy.etchZoltuFactory(vm);
        address deployed = LibRainDeploy.deployZoltu(type(St0xAttestSubParser).creationCode);
        assertEq(deployed, LibProdDeployV4.ST0X_ATTEST_SUB_PARSER_CANDIDATE);
        assertTrue(deployed.code.length > 0);
        assertEq(deployed.codehash, LibProdDeployV4.ST0X_ATTEST_SUB_PARSER_CODEHASH_CANDIDATE);
    }

    // --- Non-deployed-contract constants ---

    /// The beacon initial owner is rainlang.eth and unchanged across versions.
    function testBeaconInitialOwner() external pure {
        assertEq(LibProdDeployV4.BEACON_INITIAL_OWNER, address(0x8E4bdeec7CEB9570D440676345dA1dCe10329f5b));
    }

    /// The committed `candidate` snapshot MUST match the current source: the
    /// stored per-contract CREATION_CODE constant equals `type(C).creationCode`.
    /// Fails if the source changes without regenerating `candidate` via
    /// `forge script ./script/BuildPointers.sol`. Pure-forge; no git/shell.
    function testCandidateSelfConsistent() external pure {
        assertEq(LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_CANDIDATE, type(StoxReceipt).creationCode);
        assertEq(LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_CANDIDATE, type(StoxReceiptVault).creationCode);
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CREATION_CODE_CANDIDATE, type(StoxWrappedTokenVault).creationCode
        );
        assertEq(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CREATION_CODE_CANDIDATE, type(StoxUnifiedDeployer).creationCode);
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CREATION_CODE_CANDIDATE,
            type(StoxWrappedTokenVaultBeacon).creationCode
        );
        assertEq(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_CANDIDATE,
            type(StoxWrappedTokenVaultBeaconSetDeployer).creationCode
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_CANDIDATE,
            type(StoxOffchainAssetReceiptVaultBeaconSetDeployer).creationCode
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CREATION_CODE_CANDIDATE,
            type(StoxOffchainAssetReceiptVaultAuthorizerV1).creationCode
        );
        assertEq(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CREATION_CODE_CANDIDATE,
            type(StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1).creationCode
        );
        assertEq(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CREATION_CODE_CANDIDATE,
            type(StoxCorporateActionsFacet).creationCode
        );
        assertEq(LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_CANDIDATE, type(ST0xOrchestrator).creationCode);
        assertEq(
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CREATION_CODE_CANDIDATE,
            type(ST0xOrchestratorBeaconSetDeployer).creationCode
        );
        assertEq(LibProdDeployV4.ST0X_ATTEST_SUB_PARSER_CREATION_CODE_CANDIDATE, type(St0xAttestSubParser).creationCode);
    }

    /// The V4 authoriser clone address literal and its codehash. The
    /// live-chain codehash cross-check runs in `StoxProdV4PostSwap.t.sol`.
    function testAuthoriserV4ClonePin() external pure {
        assertEq(
            LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE,
            address(0x315b16faa6eE413faBCa877d3851B3818369f0cD),
            "clone address pin drifted from the deployed literal"
        );
        // The clone codehash derives from the V4 impl address (the EIP-1167
        // runtime embeds it).
        assertEq(
            LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH,
            keccak256(
                abi.encodePacked(
                    ERC1167_PREFIX,
                    LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_1,
                    ERC1167_SUFFIX
                )
            ),
            "clone codehash literal drifted from the EIP-1167(impl) derivation"
        );
    }

    /// Each release's frozen runtime bytecode hashes to that release's codehash
    /// pin.
    function testTaggedRuntimeHashesToCodehash() external pure {
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_0_1_1), LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_1),
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_1
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_0_1_30), LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_30
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_30),
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_30
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_30),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_30
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_30),
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_30
        );
        assertEq(
            keccak256(LibProdDeployV4.ST0X_ORCHESTRATOR_RUNTIME_CODE_0_1_30),
            LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_30
        );
        assertEq(
            keccak256(LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_30),
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_30
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_RECEIPT_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(
                LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE_CANDIDATE
            ),
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.ST0X_ORCHESTRATOR_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_CANDIDATE
        );
        assertEq(
            keccak256(LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE_CANDIDATE),
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE
        );
    }

    // =========================================================================
    // Frozen-record redeploy reproducibility (no fork).
    //
    // Deploying the frozen `X_CREATION_CODE_<tag>` record in `LibProdDeployV4`
    // through the Zoltu factory lands at the frozen `X_<tag>` address holding
    // the frozen `X_RUNTIME_CODE_<tag>` bytecode with the frozen
    // `X_CODEHASH_<tag>`.
    //
    // Only distinct (creation code, address) pairs are covered: candidate
    // contracts byte-identical to their 0.1.1 counterparts Zoltu-derive the
    // same address and would collide on redeploy.
    //
    // A deployer/beacon whose constructor bakes an impl address needs that
    // impl's frozen creation code deployed first.
    // =========================================================================

    /// Deploys `creationCode` through the Zoltu factory and asserts the deploy
    /// reproduces the frozen address, full runtime bytecode, and codehash.
    function _assertFrozenRedeploy(
        bytes memory creationCode,
        address expectedAddress,
        bytes memory expectedRuntimeCode,
        bytes32 expectedCodehash
    ) internal {
        address deployed = LibRainDeploy.deployZoltu(creationCode);
        assertEq(deployed, expectedAddress);
        assertEq(deployed.code, expectedRuntimeCode);
        assertEq(deployed.codehash, expectedCodehash);
    }

    // --- 0.1.1 frozen redeploys ---

    function testFrozenRedeployStoxReceipt() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxReceiptVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxWrappedTokenVault() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxUnifiedDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_0_1_1,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_0_1_1
        );
    }

    /// The beacon's `UpgradeableBeacon` constructor validates its impl has code,
    /// so the wrapped-token-vault impl is deployed (frozen) first.
    function testFrozenRedeployStoxWrappedTokenVaultBeacon() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CREATION_CODE_0_1_1);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CODEHASH_0_1_1
        );
    }

    /// Needs the wrapped-token-vault impl and its beacon deployed (frozen)
    /// first, matching `testDeployAddressStoxWrappedTokenVaultBeaconSetDeployer`.
    function testFrozenRedeployStoxWrappedTokenVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_CREATION_CODE_0_1_1);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_CREATION_CODE_0_1_1);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
    }

    /// Its constructor builds two beacons over the receipt and receipt-vault
    /// impls, so both are deployed (frozen) first, matching
    /// `testDeployAddressStoxOffchainAssetReceiptVaultBeaconSetDeployer`.
    function testFrozenRedeployStoxOffchainAssetReceiptVaultBeaconSetDeployer() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_0_1_1);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_0_1_1);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxOffchainAssetReceiptVaultAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1_CODEHASH_0_1_1
        );
    }

    function testFrozenRedeployStoxCorporateActionsFacet() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CREATION_CODE_0_1_1,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_1,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_1,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_1
        );
    }

    // --- 0.1.30 frozen redeploys. The snapshot holds only the orchestrator's
    // on-chain dependency closure; the wrapped-token-vault chain, the
    // authorizers and the unified deployer are 0.1.1-only. All six frozen
    // contracts have a distinct (creation code, address) pair vs 0.1.1. ---

    function testFrozenRedeployStoxReceipt_0_1_30() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_0_1_30,
            LibProdDeployV4.STOX_RECEIPT_0_1_30,
            LibProdDeployV4.STOX_RECEIPT_RUNTIME_CODE_0_1_30,
            LibProdDeployV4.STOX_RECEIPT_CODEHASH_0_1_30
        );
    }

    function testFrozenRedeployStoxReceiptVault_0_1_30() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_0_1_30,
            LibProdDeployV4.STOX_RECEIPT_VAULT_0_1_30,
            LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_0_1_30,
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_0_1_30
        );
    }

    function testFrozenRedeployStoxCorporateActionsFacet_0_1_30() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CREATION_CODE_0_1_30,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_0_1_30,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_0_1_30,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_0_1_30
        );
    }

    /// Its constructor builds two beacons over the receipt and receipt-vault
    /// impls, so both are deployed (frozen, at their 0.1.30 addresses) first.
    function testFrozenRedeployStoxOffchainAssetReceiptVaultBeaconSetDeployer_0_1_30() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_0_1_30);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_0_1_30);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_30,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_0_1_30,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_30,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_0_1_30
        );
    }

    function testFrozenRedeployST0xOrchestrator_0_1_30() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_0_1_30,
            LibProdDeployV4.ST0X_ORCHESTRATOR_0_1_30,
            LibProdDeployV4.ST0X_ORCHESTRATOR_RUNTIME_CODE_0_1_30,
            LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_0_1_30
        );
    }

    /// Its constructor builds an `UpgradeableBeacon` over the orchestrator impl,
    /// so the impl is deployed (frozen, at its 0.1.30 address) first.
    function testFrozenRedeployST0xOrchestratorBeaconSetDeployer_0_1_30() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_0_1_30);
        _assertFrozenRedeploy(
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CREATION_CODE_0_1_30,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_0_1_30,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE_0_1_30,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_0_1_30
        );
    }

    // --- candidate frozen redeploys: the seven candidate contracts with a
    // distinct (creation code, address) pair vs 0.1.1 — the corporate-actions
    // facet, receipt vault, OARV beacon-set deployer, unified deployer,
    // orchestrator, orchestrator beacon-set deployer, and wrapped-token-vault
    // beacon-set deployer. An impl a constructor bakes is deployed (frozen, at
    // its candidate address) first. ---

    /// No beacon bytecode is baked into the deployer artifact, so no impl
    /// predeploy is needed.
    function testFrozenRedeployStoxWrappedTokenVaultBeaconSetDeployer_CANDIDATE() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_CANDIDATE,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CANDIDATE,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_CANDIDATE,
            LibProdDeployV4.STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE
        );
    }

    function testFrozenRedeployStoxCorporateActionsFacet_CANDIDATE() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CREATION_CODE_CANDIDATE,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CANDIDATE,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_RUNTIME_CODE_CANDIDATE,
            LibProdDeployV4.STOX_CORPORATE_ACTIONS_FACET_CODEHASH_CANDIDATE
        );
    }

    function testFrozenRedeployStoxReceiptVault_CANDIDATE() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_CANDIDATE,
            LibProdDeployV4.STOX_RECEIPT_VAULT_CANDIDATE,
            LibProdDeployV4.STOX_RECEIPT_VAULT_RUNTIME_CODE_CANDIDATE,
            LibProdDeployV4.STOX_RECEIPT_VAULT_CODEHASH_CANDIDATE
        );
    }

    /// Its constructor builds two beacons over the receipt and receipt-vault
    /// impls, so both are deployed (frozen, at their candidate addresses) first.
    function testFrozenRedeployStoxOffchainAssetReceiptVaultBeaconSetDeployer_CANDIDATE() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_CREATION_CODE_CANDIDATE);
        LibRainDeploy.deployZoltu(LibProdDeployV4.STOX_RECEIPT_VAULT_CREATION_CODE_CANDIDATE);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CREATION_CODE_CANDIDATE,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CANDIDATE,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_RUNTIME_CODE_CANDIDATE,
            LibProdDeployV4.STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE
        );
    }

    function testFrozenRedeployStoxUnifiedDeployer_CANDIDATE() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CREATION_CODE_CANDIDATE,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CANDIDATE,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_RUNTIME_CODE_CANDIDATE,
            LibProdDeployV4.STOX_UNIFIED_DEPLOYER_CODEHASH_CANDIDATE
        );
    }

    function testFrozenRedeployST0xOrchestrator_CANDIDATE() external {
        LibRainDeploy.etchZoltuFactory(vm);
        _assertFrozenRedeploy(
            LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_CANDIDATE,
            LibProdDeployV4.ST0X_ORCHESTRATOR_CANDIDATE,
            LibProdDeployV4.ST0X_ORCHESTRATOR_RUNTIME_CODE_CANDIDATE,
            LibProdDeployV4.ST0X_ORCHESTRATOR_CODEHASH_CANDIDATE
        );
    }

    /// Its constructor builds an `UpgradeableBeacon` over the orchestrator impl,
    /// so the impl is deployed (frozen, at its candidate address) first.
    function testFrozenRedeployST0xOrchestratorBeaconSetDeployer_CANDIDATE() external {
        LibRainDeploy.etchZoltuFactory(vm);
        LibRainDeploy.deployZoltu(LibProdDeployV4.ST0X_ORCHESTRATOR_CREATION_CODE_CANDIDATE);
        _assertFrozenRedeploy(
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CREATION_CODE_CANDIDATE,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CANDIDATE,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_RUNTIME_CODE_CANDIDATE,
            LibProdDeployV4.ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER_CODEHASH_CANDIDATE
        );
    }
}
