// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Script} from "forge-std-1.16.1/src/Script.sol";
import {LibCodeGen} from "rain-sol-codegen-0.1.0/src/lib/LibCodeGen.sol";
import {LibFs} from "rain-sol-codegen-0.1.0/src/lib/LibFs.sol";
import {LibRainDeploy} from "rain-deploy-0.1.4/src/lib/LibRainDeploy.sol";
import {StoxReceipt} from "../src/concrete/StoxReceipt.sol";
import {StoxReceiptVault} from "../src/concrete/StoxReceiptVault.sol";
import {StoxCorporateActionsFacet} from "../src/concrete/StoxCorporateActionsFacet.sol";
import {StoxWrappedTokenVault} from "../src/concrete/StoxWrappedTokenVault.sol";
import {StoxUnifiedDeployer} from "../src/concrete/deploy/StoxUnifiedDeployer.sol";
import {StoxWrappedTokenVaultBeacon} from "../src/concrete/StoxWrappedTokenVaultBeacon.sol";
import {
    StoxWrappedTokenVaultBeaconSetDeployer
} from "../src/concrete/deploy/StoxWrappedTokenVaultBeaconSetDeployer.sol";
import {
    StoxOffchainAssetReceiptVaultBeaconSetDeployer
} from "../src/concrete/deploy/StoxOffchainAssetReceiptVaultBeaconSetDeployer.sol";
import {
    StoxOffchainAssetReceiptVaultAuthorizerV1
} from "../src/concrete/authorize/StoxOffchainAssetReceiptVaultAuthorizerV1.sol";
import {
    StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1
} from "../src/concrete/authorize/StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1.sol";
import {ST0xOrchestrator} from "../src/concrete/ST0xOrchestrator.sol";
import {ST0xOrchestratorBeaconSetDeployer} from "../src/concrete/deploy/ST0xOrchestratorBeaconSetDeployer.sol";

contract BuildPointers is Script {
    /// @notice The canonical release tag. Read from `foundry.toml`
    /// `[package].version` — the single source of truth — with dots converted
    /// to underscores for the Solidity constant/dir form (`0.1.3` -> `0_1_3`).
    /// Everything version-dependent (the `<tag>/` snapshot dir, `DEPLOY_TAG`,
    /// the current-release aliases) derives from this.
    function deployTag() internal view returns (string memory) {
        string memory version = vm.parseTomlString(vm.readFile("foundry.toml"), ".package.version");
        bytes memory b = bytes(version);
        bytes memory out = new bytes(b.length);
        for (uint256 i = 0; i < b.length; i++) {
            out[i] = b[i] == "." ? bytes1("_") : b[i];
        }
        return string(out);
    }

    /// @notice One unversioned current-release alias pair (address + codehash)
    /// referencing the versioned constant for `tag` in `LibProdDeployV4`.
    function currentAlias(string memory base, string memory tag) internal pure returns (string memory) {
        string memory addr = string.concat("    address constant ", base, " = LibProdDeployV4.", base, "_", tag, ";\n");
        string memory hash = string.concat(
            "    bytes32 constant ", base, "_CODEHASH = LibProdDeployV4.", base, "_CODEHASH_", tag, ";\n"
        );
        return string.concat(addr, hash);
    }

    /// @notice Generate `src/generated/LibProdDeployCurrent.sol`: unversioned
    /// aliases of the current release's versioned constants, so production
    /// references a stable name that never needs hand-editing on a version bump
    /// yet only ever resolves to a published release. Regenerated from the
    /// canonical `deployTag()`; `git-clean` enforces it stays in sync.
    function buildCurrentLib() internal {
        string memory tag = deployTag();
        // Adjacent string literals concatenate at compile time, so each
        // `string.concat` here has few dynamic args — keeps the script's stack
        // shallow (this file compiles without via_ir).
        string memory head = string.concat(
            "// SPDX-License-Identifier: LicenseRef-DCL-1.0\n"
            "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd\n"
            "pragma solidity ^0.8.25;\n\n" "import {LibProdDeployV4} from \"../lib/LibProdDeployV4.sol\";\n\n"
            "/// @notice GENERATED by script/BuildPointers.sol from foundry.toml\n"
            "/// [package].version. Do not edit. Each constant is an unversioned\n"
            "/// alias of the current release's versioned constant in\n"
            "/// LibProdDeployV4 (which imports the frozen src/generated/<tag>/\n"
            "/// snapshot), so production references a stable name that only ever\n"
            "/// resolves to a published release.\n" "library LibProdDeployCurrent {\n"
            "    string constant DEPLOY_TAG = \"",
            tag,
            "\";\n\n"
        );
        string memory tail = "\n    address constant BEACON_INITIAL_OWNER = LibProdDeployV4.BEACON_INITIAL_OWNER;\n"
            "    address constant STOX_PROD_AUTHORISER_V4_CLONE = LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE;\n"
            "    bytes32 constant STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH =\n"
            "        LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH;\n" "}\n";
        vm.writeFile("src/generated/LibProdDeployCurrent.sol", string.concat(head, currentLibAliases(tag), tail));
    }

    /// @notice The 12 deployed contracts' unversioned alias pairs, split across
    /// two `string.concat`s to keep the stack shallow.
    function currentLibAliases(string memory tag) internal pure returns (string memory) {
        string memory out = currentAlias("STOX_RECEIPT", tag);
        out = string.concat(out, currentAlias("STOX_RECEIPT_VAULT", tag));
        out = string.concat(out, currentAlias("STOX_WRAPPED_TOKEN_VAULT", tag));
        out = string.concat(out, currentAlias("STOX_UNIFIED_DEPLOYER", tag));
        out = string.concat(out, currentAlias("STOX_WRAPPED_TOKEN_VAULT_BEACON", tag));
        out = string.concat(out, currentAlias("STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER", tag));
        out = string.concat(out, currentAlias("STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER", tag));
        out = string.concat(out, currentAlias("STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1", tag));
        out = string.concat(out, currentAlias("STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1", tag));
        out = string.concat(out, currentAlias("STOX_CORPORATE_ACTIONS_FACET", tag));
        out = string.concat(out, currentAlias("ST0X_ORCHESTRATOR", tag));
        out = string.concat(out, currentAlias("ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER", tag));
        return out;
    }

    function addressConstantString(address addr) internal pure returns (string memory) {
        return string.concat(
            "\n",
            "/// @dev The deterministic deploy address of the contract when deployed via\n",
            "/// the Zoltu factory.\n",
            "address constant DEPLOYED_ADDRESS = address(",
            vm.toString(addr),
            ");\n"
        );
    }

    /// @notice Deploys a contract via the Zoltu factory and generates its
    /// pointer file containing `DEPLOYED_ADDRESS`, `CREATION_CODE`, and
    /// `RUNTIME_CODE` constants.
    /// @param name Must exactly match the contract's Solidity filename (without
    /// `.sol`), as it determines the generated pointer file path under
    /// `src/generated/<tag>/` — the frozen per-release snapshot for the current
    /// `deployTag()` (read from the canonical `foundry.toml` version). Historical
    /// tags are never regenerated; a release bump writes a new `<tag>/` snapshot
    /// beside them.
    /// @param creationCode The creation bytecode of the contract, typically
    /// obtained via `type(ContractName).creationCode`.
    function buildContractPointers(string memory name, bytes memory creationCode) internal {
        address deployed = LibRainDeploy.deployZoltu(creationCode);

        LibFs.buildFileForContract(
            vm,
            deployed,
            string.concat(deployTag(), "/", name),
            string.concat(
                addressConstantString(deployed),
                LibCodeGen.bytesConstantString(
                    vm, "/// @dev The creation bytecode of the contract.", "CREATION_CODE", creationCode
                ),
                LibCodeGen.bytesConstantString(
                    vm, "/// @dev The runtime bytecode of the contract.", "RUNTIME_CODE", deployed.code
                )
            )
        );
    }

    function run() external {
        LibRainDeploy.etchZoltuFactory(vm);

        buildContractPointers("StoxCorporateActionsFacet", type(StoxCorporateActionsFacet).creationCode);
        buildContractPointers("StoxReceipt", type(StoxReceipt).creationCode);
        buildContractPointers("StoxReceiptVault", type(StoxReceiptVault).creationCode);
        buildContractPointers("StoxWrappedTokenVault", type(StoxWrappedTokenVault).creationCode);
        // Beacon must be built before the deployer since the deployer imports
        // the beacon's pointer file.
        buildContractPointers("StoxWrappedTokenVaultBeacon", type(StoxWrappedTokenVaultBeacon).creationCode);
        buildContractPointers(
            "StoxWrappedTokenVaultBeaconSetDeployer", type(StoxWrappedTokenVaultBeaconSetDeployer).creationCode
        );
        // OARV deployer depends on StoxReceipt and StoxReceiptVault pointers.
        buildContractPointers(
            "StoxOffchainAssetReceiptVaultBeaconSetDeployer",
            type(StoxOffchainAssetReceiptVaultBeaconSetDeployer).creationCode
        );
        buildContractPointers("StoxUnifiedDeployer", type(StoxUnifiedDeployer).creationCode);
        // Authorizers have no dependencies on other Stox contracts.
        buildContractPointers(
            "StoxOffchainAssetReceiptVaultAuthorizerV1", type(StoxOffchainAssetReceiptVaultAuthorizerV1).creationCode
        );
        buildContractPointers(
            "StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1",
            type(StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1).creationCode
        );
        // ST0x orchestrator. The beacon-set deployer's constructor bakes the
        // orchestrator impl constant, so the impl must be built (and thus
        // Zoltu-deployed at that address) before the deployer.
        buildContractPointers("ST0xOrchestrator", type(ST0xOrchestrator).creationCode);
        buildContractPointers("ST0xOrchestratorBeaconSetDeployer", type(ST0xOrchestratorBeaconSetDeployer).creationCode);

        // Regenerate the unversioned current-release alias lib from the canonical
        // version, after all `<tag>/` snapshots (which its aliases resolve to).
        buildCurrentLib();
    }
}
