#!/usr/bin/env bash
set -euo pipefail

# check-published-deploy-constants.sh
#
# Guards the deploy-address mirror between the generated Zoltu pointer files
# and the hand-maintained production deploy library.
#
# Every `src/generated/*.pointers.sol` file is regenerated by
# `script/BuildPointers.sol` and declares the deterministic Zoltu deploy
# address of one contract as its `DEPLOYED_ADDRESS` constant. The production
# library `src/lib/LibProdDeployV4.sol` re-pins each of those addresses by hand
# as a named production constant (e.g. `STOX_RECEIPT_0_1_2`). Those
# two are the same value written in two places, so they can silently drift: a
# newly generated pointer whose `LibProdDeployV4` constant was forgotten, or a
# pointer address that moved after a dependency bump while the lib literal was
# left stale, both break the mirror without any single file looking wrong.
# This check fails in exactly that case — every generated `DEPLOYED_ADDRESS`
# must appear, verbatim, as an `address(0x...)` literal in `LibProdDeployV4`.
#
# It is purely local: it only reads files already in the working tree using
# grep and POSIX tools — no `cast`, no network, no FFI (st0x CI runs no FFI).
# Deploy addresses are EIP-55 checksummed, so the hex is compared
# case-insensitively to avoid false negatives from checksum casing.
#
# Modelled on raindex's `script/check-published-deploy-constants.sh`, but
# adapted: raindex fetches published soldeer versions over the network and
# drives the check through `vm.ffi` from a forge test; st0x has no FFI and its
# constants mirror local generated pointers, so this variant is a standalone,
# offline, pointer-driven shell check wired directly into CI.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
lib_file="${repo_root}/src/lib/LibProdDeployV4.sol"
generated_dir="${repo_root}/src/generated"

missing=()

for pointer_file in "${generated_dir}"/*.pointers.sol "${generated_dir}"/*/*.pointers.sol; do
    # Extract the 40-hex address from the `DEPLOYED_ADDRESS` declaration, if the
    # pointer file has one. Format:
    #   address constant DEPLOYED_ADDRESS = address(0x<40 hex>);
    address="$(grep -oE 'DEPLOYED_ADDRESS = address\(0x[0-9a-fA-F]{40}\)' "${pointer_file}" \
        | grep -oE '0x[0-9a-fA-F]{40}' || true)"
    if [ -z "${address}" ]; then
        continue
    fi

    pointer_name="$(basename "${pointer_file}" .pointers.sol)"

    # `LibProdDeployV4` must pin the exact same address literal somewhere.
    # Compare case-insensitively because the addresses are EIP-55 checksummed.
    if ! grep -iqF "address(${address})" "${lib_file}"; then
        missing+=("${pointer_name}(${address})")
    fi
done

if [ "${#missing[@]}" -gt 0 ]; then
    echo "MISSING: ${missing[*]}"
    exit 1
fi

echo "OK"
