#!/usr/bin/env python3
"""Generate the prod deploy libs from the frozen per-release snapshots.

- `src/generated/LibProdDeployV4.sol`: one versioned constant set per release tag
  (a `src/generated/<tag>/` dir), each aliasing that tag's frozen
  `*.pointers.sol` exports. Regenerated wholesale from the snapshots every run, so
  a released tag's records can never drift (its snapshot is frozen).
- `src/generated/LibProdDeployCurrent.sol`: unversioned aliases of the CURRENT
  release (the `[package].version` in foundry.toml — the next, in-development
  version), so production references a stable name that only ever resolves to a
  release's pinned constants.

`BuildPointers.sol` writes the `<tag>/` snapshot for the current version first;
this then generates the libs from all `<tag>/` dirs. git-clean enforces both.
"""
import os, re, sys

GEN = "src/generated"
OWNER = "0x8E4bdeec7CEB9570D440676345dA1dCe10329f5b"

# (pointer filename without .sol, constant BASE) in a fixed order.
CONTRACTS = [
    ("StoxReceipt", "STOX_RECEIPT"),
    ("StoxReceiptVault", "STOX_RECEIPT_VAULT"),
    ("StoxWrappedTokenVault", "STOX_WRAPPED_TOKEN_VAULT"),
    ("StoxUnifiedDeployer", "STOX_UNIFIED_DEPLOYER"),
    ("StoxWrappedTokenVaultBeacon", "STOX_WRAPPED_TOKEN_VAULT_BEACON"),
    ("StoxWrappedTokenVaultBeaconSetDeployer", "STOX_WRAPPED_TOKEN_VAULT_BEACON_SET_DEPLOYER"),
    ("StoxOffchainAssetReceiptVaultBeaconSetDeployer", "STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_BEACON_SET_DEPLOYER"),
    ("StoxOffchainAssetReceiptVaultAuthorizerV1", "STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_AUTHORIZER_V1"),
    ("StoxOffchainAssetReceiptVaultPaymentMintAuthorizerV1", "STOX_OFFCHAIN_ASSET_RECEIPT_VAULT_PAYMENT_MINT_AUTHORIZER_V1"),
    ("StoxCorporateActionsFacet", "STOX_CORPORATE_ACTIONS_FACET"),
    ("ST0xOrchestrator", "ST0X_ORCHESTRATOR"),
    ("ST0xOrchestratorBeaconSetDeployer", "ST0X_ORCHESTRATOR_BEACON_SET_DEPLOYER"),
]

HEADER = (
    "// SPDX-License-Identifier: LicenseRef-DCL-1.0\n"
    "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd\n"
    "pragma solidity ^0.8.25;\n\n"
    "// GENERATED by script/gen_prod_libs.py. Do not edit.\n"
)


def current_tag():
    v = re.search(r'(?m)^\s*version\s*=\s*"([^"]+)"', open("foundry.toml").read()).group(1)
    return v.replace(".", "_")


def tags():
    ts = [d for d in os.listdir(GEN) if re.fullmatch(r"\d+_\d+_\d+", d) and os.path.isdir(f"{GEN}/{d}")]
    return sorted(ts, key=lambda t: tuple(int(x) for x in t.split("_")))


def contracts_for(tag):
    return [(n, b) for n, b in CONTRACTS if os.path.exists(f"{GEN}/{tag}/{n}.pointers.sol")]


def gen_v4():
    out = [HEADER]
    for tag in tags():
        for name, base in contracts_for(tag):
            out.append(
                f"import {{DEPLOYED_ADDRESS as {base}_ADDRESS_{tag}_GEN, BYTECODE_HASH as {base}_CODEHASH_{tag}_GEN,"
                f" CREATION_CODE as {base}_CREATION_{tag}_GEN, RUNTIME_CODE as {base}_RUNTIME_{tag}_GEN}}"
                f' from "./{tag}/{name}.pointers.sol";\n'
            )
    out.append("\nlibrary LibProdDeployV4 {\n")
    out.append(f"    address constant BEACON_INITIAL_OWNER = address({OWNER});\n")
    out.append("    address constant STOX_PROD_AUTHORISER_V4_CLONE = address(0);\n")
    out.append("    bytes32 constant STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH = bytes32(0);\n")
    for tag in tags():
        for name, base in contracts_for(tag):
            out.append(f"    address constant {base}_{tag} = {base}_ADDRESS_{tag}_GEN;\n")
            out.append(f"    bytes32 constant {base}_CODEHASH_{tag} = {base}_CODEHASH_{tag}_GEN;\n")
            out.append(f"    bytes constant {base}_CREATION_CODE_{tag} = {base}_CREATION_{tag}_GEN;\n")
            out.append(f"    bytes constant {base}_RUNTIME_CODE_{tag} = {base}_RUNTIME_{tag}_GEN;\n")
    out.append("}\n")
    open(f"{GEN}/LibProdDeployV4.sol", "w").write("".join(out))


def gen_current():
    tag = current_tag()
    if not os.path.isdir(f"{GEN}/{tag}"):
        sys.exit(f"gen_prod_libs: current version dir {GEN}/{tag} missing (run BuildPointers first)")
    out = [HEADER, 'import {LibProdDeployV4} from "./LibProdDeployV4.sol";\n\n']
    out.append("library LibProdDeployCurrent {\n")
    out.append(f'    string constant DEPLOY_TAG = "{tag}";\n')
    out.append("    address constant BEACON_INITIAL_OWNER = LibProdDeployV4.BEACON_INITIAL_OWNER;\n")
    out.append("    address constant STOX_PROD_AUTHORISER_V4_CLONE = LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE;\n")
    out.append(
        "    bytes32 constant STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH ="
        " LibProdDeployV4.STOX_PROD_AUTHORISER_V4_CLONE_CODEHASH;\n"
    )
    for name, base in contracts_for(tag):
        out.append(f"    address constant {base} = LibProdDeployV4.{base}_{tag};\n")
        out.append(f"    bytes32 constant {base}_CODEHASH = LibProdDeployV4.{base}_CODEHASH_{tag};\n")
    out.append("}\n")
    open(f"{GEN}/LibProdDeployCurrent.sol", "w").write("".join(out))


if __name__ == "__main__":
    gen_v4()
    gen_current()
    print(f"generated LibProdDeployV4 ({len(tags())} tags) + LibProdDeployCurrent (tag {current_tag()})")
