name: rainix-sol
on: [push]
jobs:
  rainix-sol:
    uses: rainlanguage/rainix/.github/workflows/rainix-sol.yaml@main
    secrets:
      RPC_URL_ARBITRUM_FORK: ${{ secrets.RPC_URL_ARBITRUM_FORK }}
      RPC_URL_BASE_FORK: ${{ secrets.RPC_URL_BASE_FORK }}
      RPC_URL_BASE_SEPOLIA_FORK: ${{ secrets.RPC_URL_BASE_SEPOLIA_FORK }}
      RPC_URL_ETHEREUM_FORK: ${{ secrets.RPC_URL_ETHEREUM_FORK }}
      RPC_URL_FLARE_FORK: ${{ secrets.RPC_URL_FLARE_FORK }}
      RPC_URL_POLYGON_FORK: ${{ secrets.RPC_URL_POLYGON_FORK }}
